server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.127.128
cart:
  jwt:
    publicKeyPath: F:\\project\\temp\\rsa.pub
    cookieName: GMALL_TOKEN
    userKeyName: USER-KEY
    expire: 2912000