server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
auth:
  jwt:
    publicKeyPath: F:\\project\\temp\\rsa.pub
    privateKeyPath: F:\\project\\temp\\rsa.pri
    expire: 2592000  # 单位分钟
    cookieName: GMALL_TOKEN
    secret: 2340p0LJI@#@$OLldsjkl24esd